stages:
  - build
  - validation
  - submission

compileJava:
  stage: build
  script: chmod +x gradlew && ./gradlew compileJava
  only: ['tags']

compileTestJava:
  stage: build
  script: chmod +x gradlew && ./gradlew compileTestJava
  only: ['tags']

check-files:
  stage: validation
  script: chmod +x gradlew && ./gradlew checkFiles
  only: ['tags']

javadoc:
  stage: validation
  script: chmod +x gradlew && ./gradlew javadoc
  only: ['tags']

submit-hw5-1:
  stage: submission
  script: git checkout hw5-part1-final
  only: ['tags']